#####################################################################################
#  Lumenfall Shaders - entity ids (entityId uniform)
#####################################################################################

entity.50001 = lightning_bolt
entity.50002 = glow_squid magma_cube blaze allay vex experience_orb
entity.50003 = end_crystal
