/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsNewRouteImport } from './routes/items.new'
import { Route as ItemsItemIdIndexRouteImport } from './routes/items.$itemId.index'
import { Route as ItemsItemIdEditRouteImport } from './routes/items.$itemId.edit'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsNewRoute = ItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdIndexRoute = ItemsItemIdIndexRouteImport.update({
  id: '/items/$itemId/',
  path: '/items/$itemId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdEditRoute = ItemsItemIdEditRouteImport.update({
  id: '/items/$itemId/edit',
  path: '/items/$itemId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/items/new': typeof ItemsNewRoute
  '/items/$itemId/edit': typeof ItemsItemIdEditRoute
  '/items/$itemId/': typeof ItemsItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/items/new': typeof ItemsNewRoute
  '/items/$itemId/edit': typeof ItemsItemIdEditRoute
  '/items/$itemId': typeof ItemsItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/items/new': typeof ItemsNewRoute
  '/items/$itemId/edit': typeof ItemsItemIdEditRoute
  '/items/$itemId/': typeof ItemsItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/categories'
    | '/sitemap.xml'
    | '/stats'
    | '/items/new'
    | '/items/$itemId/edit'
    | '/items/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/categories'
    | '/sitemap.xml'
    | '/stats'
    | '/items/new'
    | '/items/$itemId/edit'
    | '/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/categories'
    | '/sitemap.xml'
    | '/stats'
    | '/items/new'
    | '/items/$itemId/edit'
    | '/items/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  CategoriesRoute: typeof CategoriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  ItemsNewRoute: typeof ItemsNewRoute
  ItemsItemIdEditRoute: typeof ItemsItemIdEditRoute
  ItemsItemIdIndexRoute: typeof ItemsItemIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/new': {
      id: '/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof ItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId/': {
      id: '/items/$itemId/'
      path: '/items/$itemId'
      fullPath: '/items/$itemId/'
      preLoaderRoute: typeof ItemsItemIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId/edit': {
      id: '/items/$itemId/edit'
      path: '/items/$itemId/edit'
      fullPath: '/items/$itemId/edit'
      preLoaderRoute: typeof ItemsItemIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  CategoriesRoute: CategoriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  ItemsNewRoute: ItemsNewRoute,
  ItemsItemIdEditRoute: ItemsItemIdEditRoute,
  ItemsItemIdIndexRoute: ItemsItemIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
