/*
    Lumenfall - noise & hashing
    noisetex (256x256, generated by tools/make_noise.py):
        r = white noise, g = r shifted by (37,17) for the 3D slice trick,
        b = blue noise, a = independent white noise
*/

uniform sampler2D noisetex;
const int noiseTextureResolution = 256;

float hash12(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}
vec2 hash22(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * vec3(0.1031, 0.1030, 0.0973));
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.xx + p3.yz) * p3.zy);
}
float hash13(vec3 p3) {
    p3 = fract(p3 * 0.1031);
    p3 += dot(p3, p3.zyx + 31.32);
    return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
    p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
    p3 += dot(p3, p3.yxz + 33.33);
    return fract((p3.xxy + p3.yxx) * p3.zyx);
}

// Per-pixel blue noise, animated with the golden ratio so TAA integrates it
float blueNoise(vec2 fragCoord) {
    float n = texelFetch(noisetex, ivec2(fragCoord) & 255, 0).b;
    #ifdef TAA
        n = fract(n + float(frameCounter & 1023) * PHI_INV);
    #endif
    return n;
}
vec2 blueNoise2(vec2 fragCoord) {
    vec2 n = vec2(texelFetch(noisetex, ivec2(fragCoord) & 255, 0).b,
                  texelFetch(noisetex, (ivec2(fragCoord) + ivec2(97, 41)) & 255, 0).b);
    #ifdef TAA
        n = fract(n + float(frameCounter & 1023) * vec2(PHI_INV, 0.7548776662));
    #endif
    return n;
}

// Smooth 2D value noise from the texture
float noise2D(vec2 p) {
    return textureLod(noisetex, p / 256.0, 0.0).r;
}

// Smooth 3D value noise using the shifted-channel trick (one bilinear fetch)
float noise3D(vec3 p) {
    vec3 i = floor(p);
    vec3 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    vec2 uv = (i.xy + vec2(37.0, 17.0) * i.z) + f.xy;
    vec2 rg = textureLod(noisetex, (uv + 0.5) / 256.0, 0.0).rg; // g(uv) = r(uv + (37,17)) = next slice
    return mix(rg.x, rg.y, f.z);
}

float fbm2D(vec2 p, int octaves) {
    float s = 0.0, a = 0.5, w = 0.0;
    for (int i = 0; i < octaves; i++) {
        s += noise2D(p) * a;
        w += a;
        p = mat2(1.6, 1.2, -1.2, 1.6) * p;
        a *= 0.5;
    }
    return s / w;
}

float fbm3D(vec3 p, int octaves) {
    float s = 0.0, a = 0.5, w = 0.0;
    for (int i = 0; i < octaves; i++) {
        s += noise3D(p) * a;
        w += a;
        p = p * 2.03 + vec3(0.13, 0.71, 0.37);
        a *= 0.5;
    }
    return s / w;
}

// Cellular (Worley) noise in 2D, returns F1 distance
float worley2D(vec2 p) {
    vec2 i = floor(p), f = fract(p);
    float d = 1.0;
    for (int y = -1; y <= 1; y++)
    for (int x = -1; x <= 1; x++) {
        vec2 g = vec2(x, y);
        vec2 o = hash22(i + g);
        vec2 r = g + o - f;
        d = min(d, dot(r, r));
    }
    return sqrt(d);
}

// Cellular (Worley) noise in 3D, returns F1 distance (0 at feature points)
float worley3D(vec3 p) {
    vec3 i = floor(p), f = fract(p);
    float d = 1.0;
    for (int z = -1; z <= 1; z++)
    for (int y = -1; y <= 1; y++)
    for (int x = -1; x <= 1; x++) {
        vec3 g = vec3(x, y, z);
        vec3 r = g + hash33(i + g) - f;
        d = min(d, dot(r, r));
    }
    return sqrt(d);
}

// Interleaved gradient noise (cheap fallback)
float ign(vec2 fragCoord) {
    float n = fract(52.9829189 * fract(dot(fragCoord, vec2(0.06711056, 0.00583715))));
    #ifdef TAA
        n = fract(n + float(frameCounter & 255) * PHI_INV);
    #endif
    return n;
}
